Controllers/OnePagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Word = Microsoft.Office.Interop.Word;
using Graph = Microsoft.Office.Interop.Graph;
using Nigeria_Reg.Models;
using Nigeria_Reg.Security;
using System.Runtime.InteropServices;
using System.Globalization;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;

namespace Nigeria_Reg.Controllers
{
    public class OnePagerController : Controller
    {
        cccmDBEntities db = new cccmDBEntities();
        //
        // GET: /OnePager/
        [AuthorizeRoles("Admin", "Manager", "Can Run Reports")]
        public ActionResult GetOnePager(string date1)
        {
            ViewBag.Active = "one";

            //ExportWord();

            ViewBag.Exception = null;

            //setViewBag
            //setViewBag();

            return View("ViewOnePager");
        }

        [HttpPost]
        public JsonResult getSSIDs(string date1)
        {
            DateTime sdate = DateTime.Parse(date1);

            DateTimeFormatInfo dfi = DateTimeFormatInfo.CurrentInfo;
            Calendar cal = dfi.Calendar;

            int week = cal.GetWeekOfYear(sdate, dfi.CalendarWeekRule, dfi.FirstDayOfWeek);

            string weekNoYear = string.Format("{0}-{1}", week, sdate.Year);

            var surveys = db.vw_surveys
                .Where(x => x.weekNoYear == weekNoYear)
                .Select(y => new {
                    ssid = y.SSID,
                    siteName = y.SSID+":"+y.SiteName//string.Format("{0}-{1}",y.SSID, y.SiteName)
                }).ToList();

            var ssids = new SelectList(surveys, "ssid", "siteName");

            //var lgas = new SelectList(db.tlkp_Lga.Where(x => x.state_code.Equals(id)), "lga_code", "lga_name").ToList();
            return Json(ssids, JsonRequestBehavior.AllowGet);
            //return null;
        }

        private void setViewBag()
        {
            //List<SelectListItem> states = new List<SelectListItem>();

            //states.Add(new SelectListItem { Value = "", Text = "[Select State]", Selected = true });

            ////Errors errors_ =

            //foreach (vw_tlkp_State st_ in db.vw_tlkp_State)
            //{
            //    //if (new Errors(dtm_.phase).canGenerateReport())
            //    //{
            //    states.Add(new SelectListItem { Value = st_.state_code.ToString(), Text = st_.state_name });
            //    //}
            //}


            //ViewBag.StatesList = states;
        }

        //worddoc.close(ref false, ref missing, ref missing);
        private Stream GetStream(Word.Document worddoc)
        {
            //Stream fs = new MemoryStream();
            //byte[] bytes = File.ReadAllBytes(worddoc);
            ////fs.Write(bytesxx, 0, bytesxx.length)
           
            ////worddoc.get
            //fs.Position = 0;
            //return fs;
            return null;
        }

        //free the memory -- garbage collector
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }



        int[] some_colors = { 12, 3, 33, 10, 48, 37 };

        public ActionResult ExportWord(string ssid, string date1, string tokenId)
        {
            DateTime dt = DateTime.Parse(date1);

            DateTimeFormatInfo dfi = DateTimeFormatInfo.CurrentInfo;
            Calendar cal = dfi.Calendar;

            int weekno = cal.GetWeekOfYear(dt, dfi.CalendarWeekRule, dfi.FirstDayOfWeek);

            string weekNoYear = string.Format("{0}-{1}", weekno, dt.Year);


            vw_surveys s = db.vw_surveys.Where(x => x.WeekNo == weekno && x.weekNoYear == weekNoYear && x.SSID == ssid).FirstOrDefault();
            // string sql = "SELECT * FROM vw_surveys s WHERE s.WeekNo = @strWeekNo@ AND s.WeekNoYear = '@strWeekNoYear@'@strTem@;";
            vw_Basicinfo b = db.vw_Basicinfo.Where(x => x.SSID == ssid).FirstOrDefault(); ;

            spGetDemoTrend_Result[] res = db.spGetDemoTrend(ssid, weekno).ToArray();

            //count age_group
            int t1, t1_5, t6_12, t13_17, t18_59, t60p, tpct, totF, totM;

            //computations
            t1 = (s.f_lt1 ?? 0) + (s.m_lt1 ?? 0);
            t1_5 = (s.f_1_5 ?? 0) + (s.m_1_5 ?? 0);
            t6_12 = (s.f_6_12 ?? 0) + (s.m_6_12 ?? 0);
            t13_17 = (s.f_13_17 ?? 0) + (s.m_13_17 ?? 0);
            t18_59 = (s.f_18_59 ?? 0) + (s.m_18_59 ?? 0);
            t60p = (s.f_60p ?? 0) + (s.m_60p ?? 0);

            tpct = t1 + t1_5 + t6_12 + t13_17 + t18_59 + t60p;

            totF = (s.f_lt1 ?? 0) + (s.f_1_5 ?? 0) + (s.f_6_12 ?? 0) +
                  (s.f_13_17 ?? 0) + (s.f_18_59 ?? 0) + (s.f_60p ?? 0);
            totM = (s.m_lt1 ?? 0) + (s.m_1_5 ?? 0) + (s.m_6_12 ?? 0) +
                (s.m_13_17 ?? 0) + (s.m_18_59 ?? 0) + (s.m_60p ?? 0);


            int[] breakdown_tots = { t1, t1_5, t6_12, t13_17, t18_59, t60p };
            string[] breakdown_labels = { "'<1'", "'1 - 5'", "'6 - 12'", "'13 - 17'", "'18 - 59'", "'60+'" };
            int[] agg_tots = { tpct, totF, totM };
            int[] margins = { 10, 10, 20, 35, 10, 10 };

            int[] gender_colors = { 3, 41 };

            object missing = System.Reflection.Missing.Value;
            object readOnly = false;
            object isVisible = true;
            
            var applicationWord = new Word.Application();

            Word.Document worddoc;

            object fileName = HttpContext.Server.MapPath("~/ReportXlsx/template.doc");

            worddoc = applicationWord.Documents.Open(ref fileName, ref missing, ref readOnly, ref missing, ref  missing, ref missing, ref missing, ref missing, ref missing, ref missing, ref missing, ref isVisible, ref missing, ref missing, ref missing, ref missing);
                
            try
            {
                worddoc.Activate();


                int i = 1;

                //worddoc.Tables[i].Columns[3].Cells[2].Range.Text = "Site Name: " & rs("SiteName").Value & "  ===  Week: " & rs("WeekNo").Value
                docHeaderSection(s, worddoc, 1);

                //applicationWord.Visible = true;

                householdFiguresSection(s, totF, totM, worddoc, 2);

                //i = 5;
                siteBasicInfoSection(s, b, worddoc, 5);

                i = 6;

                string[] WeekDate;
                string[] N;

                trendOfIDPsSection(res, applicationWord, worddoc, 6, out WeekDate, out N);

                drawGraph1(applicationWord, worddoc, WeekDate, N);

                i = 7;
                surveyDetailsSection(s, worddoc, 7);

                demographicSection(s, t1, t1_5, t6_12, t13_17, t18_59, t60p, totF, totM, applicationWord, worddoc, 7);


                i = 8;
                ageSexBreakdownSection(t1, t1_5, t6_12, t13_17, t18_59, t60p, tpct, totF, totM, applicationWord, worddoc, 8);
                //======================================

                drawGraph2(applicationWord, worddoc, breakdown_tots, breakdown_labels, agg_tots, margins);

                drawGraph3(applicationWord, worddoc, agg_tots, gender_colors);

                i = 9;//Table CCCM

                cccmEsNFISection(s, applicationWord, worddoc, 9);

                washSection(s, applicationWord, worddoc, 11);

                protectionSection(s, applicationWord, worddoc, 13);

                educationSection(s, applicationWord, worddoc, 15);

                healthNutritionSection(s, applicationWord, worddoc, 17);

                i = 6;// 'Table Survey Details

                worddoc.Tables[i].Columns[1].Cells[3].Select();

                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 20);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 5);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 5);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 5);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
                applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 6);
                applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);

                //applicationWord.Visible = true;


                //  worddoc.savea
                //using (var entryStream = demoFile.Open())
                //{ }


                IFormatProvider culture = new System.Globalization.CultureInfo("en-GB", true);
                String date = DateTime.Now.ToShortDateString();

                date = date.Replace("/", ".");

                date = formatStrDate(date);

                //String ReportName = "cm_tracker_one_pager";
                string myName = Server.UrlEncode(ssid + "_" + weekNoYear + "_" + date + ".doc");

                // string myName = Server.UrlEncode(ReportName + ".xlsx");

Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CM Multi Sector Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.11.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/themes/base/all.css" rel="stylesheet" /> 

    @*<link href="~/Content/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-ui.js" type="text/javascript"></script>*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CM Multi Sector Tracker", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="@(ViewBag.Active == "Home" ? "active" : "")">
                    @Html.ActionLink("Home", "Index", "Home")
                    </li>

                    <li class="divider-vertical"></li>
                    <li class="@(ViewBag.Active == "SA" ? "active" : "")">
                    @Html.ActionLink("Data Entry", "Index", "Sites")
                    </li>

                    <li class="divider-vertical"></li>
                    <li class="@(ViewBag.Active == "rep" ? "active" : "")">
                        @Html.ActionLink("Reports", "ViewReport", "GenerateReport")
                    </li>

                    <li class="divider-vertical"></li>
                    <li class="@(ViewBag.Active == "one" ? "active" : "")">
                        @Html.ActionLink("One Pager", "GetOnePager", "OnePager")
                    </li>

                    <li class="divider-vertical"></li>
                    <li class="@(ViewBag.Active == "man" ? "active" : "")">
                        @Html.ActionLink("User Management", "AdminOnly", "ManageUser")
                    </li>

                    <li class="divider-vertical"></li>
                    <li class="@(ViewBag.Active == "About" ? "active" : "")">
                        @Html.ActionLink("Contact Us", "About", "Home")
                    </li>
                    <li class="divider-vertical"></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
            <p>Copyright &copy; 2016 IOM Nigeria. All rights reserved.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>