Controllers/GenerateReportController.cs
using ClosedXML.Excel;
using Nigeria_Reg.Helpers;
using Nigeria_Reg.Models;
using Nigeria_Reg.Security;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
//using Word = Microsoft.Office.Interop.Word;
//using Graph = Microsoft.Office.Interop.Graph;
//using System.IO.Compression;



namespace Nigeria_Reg.Controllers
{
    public class GenerateReportController : Controller
    {
        cccmDBEntities db = new cccmDBEntities();

        //
        // GET: /GenerateReport/
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.Active = "rep";

            return View();
        }

        [AuthorizeRoles("Admin", "Manager", "Can Run Reports")]
        public ActionResult ViewReport()
        {
            ViewBag.Active = "rep";

            //ExportWord();

            ViewBag.Exception = null;

            //setViewBag
            setViewBag();

            return View();
        }

    //    int[] some_colors = {12,3,33,10, 48,37};

    //    public ActionResult ExportWord()
    //    {
    //        vw_surveys s = db.vw_surveys.Where(x => x.WeekNo == 15 && x.weekNoYear == "15-2017" && x.SSID == "AD_S003").FirstOrDefault();
    //        // string sql = "SELECT * FROM vw_surveys s WHERE s.WeekNo = @strWeekNo@ AND s.WeekNoYear = '@strWeekNoYear@'@strTem@;";
    //        vw_Basicinfo b = db.vw_Basicinfo.Where(x => x.SSID == "AD_S003").FirstOrDefault(); ;

    //        spGetDemoTrend_Result[] res = db.spGetDemoTrend("AD_S003", 15).ToArray();

    //         //count age_group
    //        int t1, t1_5, t6_12, t13_17, t18_59, t60p, tpct, totF, totM;

    //        //computations
    //        t1 = (s.f_lt1??0) + (s.m_lt1??0);
    //        t1_5 = (s.f_1_5??0) + (s.m_1_5??0);
    //        t6_12 = (s.f_6_12??0) + (s.m_6_12??0);
    //        t13_17 = (s.f_13_17??0) + (s.m_13_17??0);
    //        t18_59 = (s.f_18_59??0) + (s.m_18_59??0);
    //        t60p = (s.f_60p??0) + (s.m_60p??0);

    //        tpct = t1 + t1_5 + t6_12 + t13_17 + t18_59 + t60p;

    //        totF = (s.f_lt1??0) + (s.f_1_5??0) + (s.f_6_12??0)+
    //              (s.f_13_17??0) + (s.f_18_59??0) + (s.f_60p??0);
    //        totM = (s.m_lt1??0) + (s.m_1_5??0) + (s.m_6_12??0) +
    //            (s.m_13_17??0) + (s.m_18_59??0) + (s.m_60p??0);


    //        int[] breakdown_tots = {t1, t1_5, t6_12, t13_17, t18_59, t60p};
    //        string[] breakdown_labels = {"'<1'", "'1 - 5'",  "'6 - 12'", "'13 - 17'", "'18 - 59'" , "'60+'"};
    //        int[] agg_tots = {tpct, totF, totM};
    //        int[] margins = { 10, 10, 20, 35, 10, 10 };

    //        int[] gender_colors = { 3, 41 };

    //        object missing = System.Reflection.Missing.Value;
    //        object readOnly = false;
    //        object isVisible = true;
    //        object fileName = HttpContext.Server.MapPath("~/ReportXlsx/template.doc");

    //        var applicationWord = new Word.Application();
    //        //applicationWord.Visible = true;


                    
    //                ///////////////////////////////////////////
    //                Word.Document worddoc;
    //                try
    //                {
    //                    worddoc = applicationWord.Documents.Open(ref fileName, ref missing, ref readOnly, ref missing, ref  missing, ref missing, ref missing, ref missing, ref missing, ref missing, ref missing, ref isVisible, ref missing, ref missing, ref missing, ref missing);
    //                    worddoc.Activate();


    //                    int i = 1;

    //                    //worddoc.Tables[i].Columns[3].Cells[2].Range.Text = "Site Name: " & rs("SiteName").Value & "  ===  Week: " & rs("WeekNo").Value
    //                    docHeaderSection(s, worddoc, 1);

    //                    //applicationWord.Visible = true;

    //                    householdFiguresSection(s, totF, totM, worddoc, 2);

    //                    //i = 5;
    //                    siteBasicInfoSection(s, b, worddoc, 5);

    //                    i = 6;

    //                    string[] WeekDate;
    //                    string[] N;

    //                    trendOfIDPsSection(res, applicationWord, worddoc, 6, out WeekDate, out N);

    //                    drawGraph1(applicationWord, worddoc, WeekDate, N);

    //                    i = 7;
    //                    surveyDetailsSection(s, worddoc, 7);

    //                    demographicSection(s, t1, t1_5, t6_12, t13_17, t18_59, t60p, totF, totM, applicationWord, worddoc, 7);


    //                    i = 8;
    //                    ageSexBreakdownSection(t1, t1_5, t6_12, t13_17, t18_59, t60p, tpct, totF, totM, applicationWord, worddoc, 8);
    //                    //======================================

    //                    drawGraph2(applicationWord, worddoc, breakdown_tots, breakdown_labels, agg_tots, margins);

    //                    drawGraph3(applicationWord, worddoc, agg_tots, gender_colors);

    //                    i = 9;//Table CCCM

    //                    cccmEsNFISection(s, applicationWord, worddoc, 9);

    //                    washSection(s, applicationWord, worddoc, 11);

    //                    protectionSection(s, applicationWord, worddoc, 13);

    //                    educationSection(s, applicationWord, worddoc, 15);

    //                    healthNutritionSection(s, applicationWord, worddoc, 17);

    //                    i = 6;// 'Table Survey Details

    //                    worddoc.Tables[i].Columns[1].Cells[3].Select();

    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 20);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 5);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 5);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 5);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 1);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);
    //                    applicationWord.Selection.MoveDown(Unit: Word.WdUnits.wdLine, Count: 6);
    //                    applicationWord.Selection.Delete(Unit: Word.WdUnits.wdCharacter, Count: 1);

    //                    applicationWord.Visible = true;


    //                    //  worddoc.savea
    //                    //using (var entryStream = demoFile.Open())
    //                    //{ }

    //                }
    //                catch (COMException ex)
    //                {
    //                    applicationWord.Quit(ref missing, ref missing, ref missing);
    //                }
    //                //Guid parameter, 


           

    //        string filePath = "~/ReportXlsx/template.doc";

            
            
    //        return null;
    //    }

    //    private void healthNutritionSection(vw_surveys s, Word.Application applicationWord, Word.Document worddoc, int i)
    //    {
    //        // '============== HEALTH & NUTRITION ====================

    //worddoc.Tables[i].Columns[2].Cells[2].Range.Text = ifstrnull(s.SupplementaryFeeding_chYN);
    
    //worddoc.Tables[i].Columns[2].Cells[2].Select();

    //        yesNoColoredInfo(applicationWord, s.SupplementaryFeeding_chYN);


    //worddoc.Tables[i].Columns[2].Cells[3].Range.Text = ifstrnull(s.SupplementaryFeeding_moYN);
    
    //worddoc.Tables[i].Columns[2].Cells[3].Select();

    //        yesNoColoredInfo(applicationWord, s.SupplementaryFeeding_moYN);

    //worddoc.Tables[i].Columns[2].Cells[4].Range.Text = ifstrnull(s.VaccinationYN);

    //worddoc.Tables[i].Columns[2].Cells[4].Select();

    //        yesNoColoredInfo(applicationWord, s.VaccinationYN);

    //worddoc.Tables[i].Columns[2].Cells[5].Range.Text = ifstrnull(s.HealthStucture_EstablishmentYN);
    
    //worddoc.Tables[i].Columns[2].Cells[5].Select();

    //        yesNoColoredInfo(applicationWord, s.HealthStucture_EstablishmentYN);

    //worddoc.Tables[i].Columns[2].Cells[6].Range.Text = ifstrnull(s.MedicalReferralsYN);
    
    //worddoc.Tables[i].Columns[2].Cells[6].Select();

    //        yesNoColoredInfo(applicationWord, s.MedicalReferralsYN);

    //worddoc.Tables[i].Columns[5].Cells[2].Range.Text = ifstrnull(s.FoodDistributionYN);
    
    //worddoc.Tables[i].Columns[5].Cells[2].Select();

    //        yesNoColoredInfo(applicationWord, s.FoodDistributionYN);

    //worddoc.Tables[i].Columns[5].Cells[3].Range.Text = ifstrnull(s.Other_activity_gYN);
    
    //worddoc.Tables[i].Columns[5].Cells[3].Select();

    //        yesNoColoredInfo(applicationWord, s.Other_activity_gYN);

Views/GenerateReport/ViewReport.cshtml
@{
    ViewBag.Title = "Download Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
}

<p style="color: White">@ViewBag.Exception</p>
@if (ViewBag.Exception != null)
{
    <p style="color: Red">@ViewBag.Exception</p>

}

<script src="../../Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
@*<script src="../../Scripts/jquery.validate.min.js" type="text/javascript"></script>*@
<script src="../../Scripts/MicrosoftAjax.js" type="text/javascript"></script>
<script src="../../Scripts/MicrosoftMvcAjax.js" type="text/javascript"></script>
@*<script type="text/javascript" src="@Url.Content("../../Scripts/jquery.cookie.js")"></script>*@


@*<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/MyCustomValidation.js" type="text/javascript"></script>

<link href="../../Content/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="../../Scripts/jquery-ui.js" type="text/javascript"></script>

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>*@


<script type="text/javascript">
    $(document).ready(function () {
        $("#date1").datepicker({
            constrainInput: true,   // prevent letters in the input field
            //minDate: new Date(),    // prevent selection of date older than today
            maxDate: new Date(),    // prevent selection of date greater than today
            //showOn: 'button',       // Show a button next to the text-field
            autoSize: true,         // automatically resize the input field
            dateFormat: 'dd/mm/yy',  // Date Format used
            //beforeShowDay: $.datepicker.noWeekends,     // Disable selection of weekends
            firstDay: 1 // Start with Monday
        });
    });

</script>


<h2>CCCM tracker report</h2>
@*<h2>@ViewBag.Title.</h2>*@

<br />

 <fieldset>
        <legend>Generate report in excel</legend>

@using (Html.BeginForm("ExportExcel", "GenerateReport", FormMethod.Post, new { id = "forma" }))
{ 
    <table class="table table-striped table-condensed table-hover">
    <tr><th>Select a date (within the week of report)</th><th>Filter by State?</th></tr>
    <tr><td>
    <div>@Html.TextBox("date1") </div>
    </td><td>
    <div>@Html.DropDownList("stateId", (List<SelectListItem>)ViewBag.StatesList)</div>
    </td></tr>

    </table>
    

    <div><input type="image" src="../../Content/Images/excel_1.jpg" class="download" /></div>
    
        
    @Html.Hidden("tokenId");
    @Html.Hidden("errorId");
}

<div id="errorMsgSt" style="display: none; color: Red">
	Need to select a state first!
</div>

<div id="errorMsgDt" style="display: none; color: Red">
	Need to select a date first!
</div>

<div id="errorNoData" style="display: none; color: Red">
	No data for current filter! Please try again...
</div>

<div class="errorMsg" style="display: none; color: Red">
	<strong>Error:</strong> No data for current filter! Please try again...
</div>

<div id="pleaseWait" style="display: none">
    <img src="../../Content/Images/PleaseWait.gif" />
	Please Wait...
</div>

</fieldset>
<hr />



<script type="text/javascript">
    //$(function () {
    //    $('#forma').submit(function (e) {

    //        if ($('#date').val() == "") {
    //            $('#errorMsgDt').show();
    //            e.preventDefault();
    //        } else {
    //            blockUIForDownload();
    //        }
    //    });
    //});

    //var fileDownloadCheckTimer;

    //function blockUIForDownload() {
    //    var token = new Date().getTime(); //use the current timestamp as the token value
    //    $('#tokenId').val(token);
    //    $('#errorMsgDt').hide();
    //    $("#pleaseWait").show();
    //    $(".download").attr("disabled", "disabled");
    //    //$.blockUI();
    //    fileDownloadCheckTimer = window.setInterval(function () {
    //        var cookieValue = $.cookie('fileDownloadToken');
    //        if (cookieValue == token)
    //            finishDownload();
    //    }, 1000);
    //}

    //function finishDownload() {
    //    window.clearInterval(fileDownloadCheckTimer);
    //    $.removeCookie('fileDownloadToken'); //clears this cookie value
    //    $("#pleaseWait").hide();
    //    $(".download").removeAttr("disabled");
    //    //$.unblockUI();
    //}
</script>

<script type="text/javascript">
    $(function () {

            $('#forma').submit(function (e) {

            if ($('#date1').val() == "") {
                $('#errorMsgSt').hide();
                $('#errorNoData').hide();
                $('#errorMsgDt').show();
                e.preventDefault();
            }

            else {
                $('#errorMsgSt').hide();
                $('#errorMsgDt').hide();
                $('#errorNoData').hide();

                blockUIForDownload();
            }
        });
    });

   function CompareDate() {
       //Note: 00 is month i.e. January
//       var dateOne = new Date(2010, 00, 15); //Year, Month, Date
//       var dateTwo = new Date(2011, 00, 15); //Year, Month, Date
       var format='mm/dd/yy';
       var dateOne = Date.parse($('#date1').val()); 
       var dateTwo = Date.parse($('#date2').val()); 
        if (dateTwo >= dateOne) {return true;} 
        else {return false;} 

    }

    var fileDownloadCheckTimer;

    function blockUIForDownload() {
        var token = new Date().getTime(); //use the current timestamp as the token value
        $('#tokenId').val(token);
        //$('#errorMsgSt').hide();
        //$("#pleaseWait").show();
        //$(".download").attr("disabled", "disabled");
        //$.blockUI();
        fileDownloadCheckTimer = window.setInterval(function () {
            var cookieValue = $.cookie('fileDownloadToken');
            if (cookieValue == token)
                finishDownload();
        }, 1000);
    }

    function finishDownload() {
        window.clearInterval(fileDownloadCheckTimer);
        $.removeCookie('fileDownloadToken'); //clears this cookie value
        //$("#pleaseWait").hide();
        //$(".download").removeAttr("disabled");
        //$.unblockUI();
    }
</script>